
name: corna
services:
  corna:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-corna
    image: registry.digitalocean.com/corna-docker-reg/corna:0.0.1
    ports:
      # host-port:container-port
      - "25060:25060"
      - "5432:5432"  # postgresql port
    expose:
      - "5001"
    deploy:
      # this will create name-service_name-number
      # if you dont give the compose file a name field it will use
      # the directory name instead
      # e.g. corna-corna-{1..3}
      replicas: 1
    environment:
      - "ANSIBLE_VAULT_PATH=${ANSIBLE_VAULT_PATH}"
      - "ANSIBLE_VAULT_PASSWORD_FILE=${ANSIBLE_VAULT_PASSWORD_FILE_IN_CONTAINER}"
      - "DB_ADDRESS=${DB_ADDRESS}"
      - "DB_USER=${DB_USER}"
      - "DB_PORT=${DB_PORT}"
      - "DB_NAME=${DB_NAME}"
      - "CORNA_PORT=${CORNA_PORT}"
      - "PICTURE_DIR=/var/www/assets"
      - "SSL_MODE=${SSL_MODE}"
    command: /usr/bin/python3.12 -m gunicorn --worker-tmp-dir=/tmp --config=gunicorn_conf.py corna.wsgi:app
    volumes:
      - "${PICTURE_DIR}:/var/www/assets:rw"
    networks:
      - backend-network
    restart: always
    healthcheck:
      # this is temp, we'll change this to a proper health
      # endpoint once it has been created
      test: curl --fail localhost:5001/frontend || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  nginx:
    depends_on:
      - corna
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-nginx
    image: registry.digitalocean.com/corna-docker-reg/corna-nginx:0.0.1
    ports:
      # we only want ports for nginx and the rest of the containers
      # will be private
      # host-port:container-port
      - "443:443"
      - "80:80"
    expose:
      - "80"
    networks:
      - backend-network
    restart: always
    healthcheck:
      # there is no point running a healthy nginx container
      # so this health check is dependent on the corna-container
      test: curl --fail corna-corna-1:5001/frontend || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

# this is not necessary but nice to explicitly declare
networks:
  backend-network:
    driver: bridge
