# Silence SQLAlchemy2.0 deprecation warnings
export SQLALCHEMY_WARN_20=0
export SQLALCHEMY_SILENCE_UBER_WARNING=1

PYTHON ?= python3.12
UV ?= uv
current_dir := $(shell pwd)

UV_SYNC_FLAGS := \
	--locked \
	--python $(PYTHON) \
	--no-managed-python \
	--no-install-project

OS := $(shell uname -s)

# Ensure that psycopg2 knows where to look for posgres on local install
# container envrionments handle this themselves
ifeq ($(OS), Darwin)
	export UV_PROJECT_ENVIRONMENT := $(current_dir)/.venv

	# PostgreSQL headers and libraries installed by Homebrew.
	export LDFLAGS := -L/opt/homebrew/opt/postgresql@13/lib
	export CPPFLAGS := -I/opt/homebrew/opt/postgresql@13/include
	export PATH := /opt/homebrew/opt/postgresql@13/bin:$(PATH)

endif

install-dev:
	$(UV) sync $(UV_SYNC_FLAGS)

install-prod:
	$(UV) sync $(UV_SYNC_FLAGS) --no-dev

check: check-coding-standards check-tests

check-coding-standards: install-dev check-pylint-main check-isort check-pycodestyle

check-pylint-main:
	$(UV) run --no-sync --python $(PYTHON) pylint corna

check-pycodestyle:
	$(UV) run --no-sync --python $(PYTHON) pycodestyle corna

check-isort:
	$(UV) run --no-sync --python $(PYTHON) isort corna --check-only --diff --skip .venv

check-tests: install-dev
	$(UV) run --no-sync --python $(PYTHON) pytest -v

node_modules:
	test -d $(current_dir)/frontend/node_modules || npm install \
		--prefix $(current_dir)/frontend

check-eslint: node_modules
	npm run lint --prefix $(current_dir)/frontend

clean: clean-python clean-js clean-caches clean-macos

clean-python:
	find . -name '*.pyc' -type f -delete
	rm -rf .venv

clean-js:
	# Remove JavaScript files generated by the TypeScript compiler.
	find frontend/public/scripts -name '*.js' -type f -delete
	rm -rf frontend/node_modules

clean-caches:
	# Remove caches generated by tests and static-analysis tools.
	find . -name '__pycache__' -type d -delete
	find . -name '.mypy_cache' -type d -delete
	find . -name '.pytest_cache' -type d -delete

clean-macos:
	# Remove AppleDouble metadata files created by macOS.
	find . -name '._*' -type f -size 4k -delete

.PHONY: install-dev install-prod check check-coding-standards \
	check-pylint-main check-pycodestyle check-isort check-tests \
	check-eslint clean clean-python clean-js clean-caches clean-macos
