"""Add support for single-use invite tokens

Revision ID: 133a86a9a6fa
Revises: e7c926c77c82
Create Date: 2026-07-26 19:25:50.580992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '133a86a9a6fa'
down_revision = 'e7c926c77c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('email_address', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', postgresql.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_user_id', postgresql.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', postgresql.UUID(), nullable=True),
    sa.CheckConstraint('redeemed_at IS NULL OR revoked_at IS NULL', name='ck_invites_not_redeemed_and_revoked'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.uuid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.uuid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invites_created_by_user_id'), 'invites', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_invites_expires_at'), 'invites', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invites_redeemed_by_user_id'), 'invites', ['redeemed_by_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_redeemed_by_user_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_expires_at'), table_name='invites')
    op.drop_index(op.f('ix_invites_created_by_user_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
