"""add support for video

Revision ID: 262b65c740ff
Revises: 29b78a584b6e
Create Date: 2024-05-15 14:26:32.937273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '262b65c740ff'
down_revision = '9fb27fb53c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('url_extension', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('orphaned', sa.Boolean(), nullable=False),
    sa.Column('image_uuid', postgresql.UUID(), nullable=True),
    sa.Column('post_uuid', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['image_uuid'], ['images.uuid'], ),
    sa.ForeignKeyConstraint(['post_uuid'], ['posts.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_media_url_extension'), 'media', ['url_extension'], unique=True)
    op.add_column('images', sa.Column('hash', sa.Text(), nullable=True))
    op.drop_index('ix_images_url_extension', table_name='images')
    op.drop_constraint('images_post_uuid_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'post_uuid')
    op.drop_column('images', 'orphaned')
    op.drop_column('images', 'url_extension')
    op.drop_column('images', 'path')
    op.drop_column('images', 'created')
    op.drop_column('images', 'size')
    op.drop_constraint('themes_thumbnail_fkey', 'themes', type_='foreignkey')
    op.create_foreign_key(None, 'themes', 'media', ['thumbnail'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.create_foreign_key('themes_thumbnail_fkey', 'themes', 'images', ['thumbnail'], ['uuid'])
    op.add_column('images', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('url_extension', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('orphaned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('post_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('images_post_uuid_fkey', 'images', 'posts', ['post_uuid'], ['uuid'])
    op.create_index('ix_images_url_extension', 'images', ['url_extension'], unique=True)
    op.drop_column('images', 'hash')
    op.drop_index(op.f('ix_media_url_extension'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
