"""add creator uuid to posts

Revision ID: 29b78a584b6e
Revises: 761c4012bb21
Create Date: 2024-04-15 14:54:42.379602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b78a584b6e'
down_revision = '761c4012bb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_uuid', postgresql.UUID(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_uuid')
    # ### end Alembic commands ###
