"""Ensure all users have an invite

Revision ID: 382aa2966661
Revises: 133a86a9a6fa
Create Date: 2026-07-26 19:29:02.273632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '382aa2966661'
down_revision = '133a86a9a6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by_user_id', postgresql.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_system_account', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_users_invited_by_user_id'), 'users', ['invited_by_user_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['invited_by_user_id'], ['uuid'], ondelete='RESTRICT')
    op.create_check_constraint(
        "ck_users_not_self_invited",
        "users",
        "invited_by_user_id IS NULL OR invited_by_user_id <> uuid",
    )

    op.create_check_constraint(
        "ck_users_invitation_origin",
        "users",
        """
        (
            is_system_account = true
            AND invited_by_user_id IS NULL
        )
        OR
        (
            is_system_account = false
            AND invited_by_user_id IS NOT NULL
        )
        """,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_users_invitation_origin",
        "users",
        type_="check",
    )

    op.drop_constraint(
        "ck_users_not_self_invited",
        "users",
        type_="check",
    )
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_invited_by_user_id'), table_name='users')
    op.drop_column('users', 'is_system_account')
    op.drop_column('users', 'invited_by_user_id')
    # ### end Alembic commands ###
