"""Add original media filename

Revision ID: 38524fed82f8
Revises: cc988693d26e
Create Date: 2026-08-14 13:45:31.358119

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '38524fed82f8'
down_revision = 'cc988693d26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('original_filename', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'original_filename')
    # ### end Alembic commands ###
