"""Add orphaned field to images

Revision ID: 4d563c46e42c
Revises: d59b5561d353
Create Date: 2024-01-12 22:00:15.998696

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4d563c46e42c'
down_revision = 'd59b5561d353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('orphaned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'orphaned')
    # ### end Alembic commands ###
