"""Add default permissions to a corna

Revision ID: 761c4012bb21
Revises: c623ddd0e03f
Create Date: 2024-04-11 16:39:30.791881

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '761c4012bb21'
down_revision = 'c623ddd0e03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corna', sa.Column('permissions', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corna', 'permissions')
    # ### end Alembic commands ###
