"""add autoincrement user number

Revision ID: 9fb27fb53c59
Revises: d5ad8dff4f17
Create Date: 2024-05-17 22:24:57.613663

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9fb27fb53c59'
down_revision = 'd5ad8dff4f17'
branch_labels = None
depends_on = None

# source for these changes: https://stackoverflow.com/q/35897254
user_number_sequence = sa.Sequence('user_number_seq') # represents the sequence


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(user_number_sequence)) # create the sequence
    op.add_column(
        'users',
        sa.Column(
            'number',
            sa.Integer(),
            user_number_sequence, # the sequence as SchemaItem
            server_default=user_number_sequence.next_value(), # next value of the sequence as default
            nullable=True,
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
      sa.schema.DropSequence(sa.Sequence('user_number_seq')))
    op.drop_column('users', 'number')
    # ### end Alembic commands ###
