"""Add derived thumbnails to media

Revision ID: c12c8789fc31
Revises: 38524fed82f8
Create Date: 2026-08-15 19:46:18.786672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c12c8789fc31'
down_revision = '38524fed82f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('thumbnail_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'media', 'media', ['thumbnail_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'thumbnail_uuid')
    # ### end Alembic commands ###
