"""Corna about

Revision ID: c2ce210a4826
Revises: 4d563c46e42c
Create Date: 2024-01-29 21:51:57.881853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2ce210a4826'
down_revision = '4d563c46e42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corna', sa.Column('about', postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corna', 'about')
    # ### end Alembic commands ###
