"""Add support for invite requests

Revision ID: cc988693d26e
Revises: 382aa2966661
Create Date: 2026-07-28 14:46:39.334165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc988693d26e'
down_revision = '382aa2966661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_requests',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('email_address', sa.Text(), nullable=False),
    sa.Column('referral_source', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'invited', 'rejected', name='invite_request_status'), server_default='pending', nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_id', postgresql.UUID(), nullable=True),
    sa.CheckConstraint(
        """
        (
            status = 'invited'
            AND invite_id IS NOT NULL
            AND reviewed_at IS NOT NULL
            AND invited_at IS NOT NULL
        )
        OR
        (
            status IN ('pending', 'rejected')
            AND invite_id IS NULL
            AND invited_at IS NULL
        )
        """,
        name="ck_invite_requests_lifecycle",
    ),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('invite_id')
    )
    op.create_index(op.f('ix_invite_requests_email_address'), 'invite_requests', ['email_address'], unique=False)
    op.create_index(op.f('ix_invite_requests_status'), 'invite_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_requests_status'), table_name='invite_requests')
    op.drop_index(op.f('ix_invite_requests_email_address'), table_name='invite_requests')
    op.drop_table('invite_requests')
    # ### end Alembic commands ###
