"""Add inner_html field

Revision ID: d59b5561d353
Revises: d0bc6ab51f9a
Create Date: 2024-01-12 21:58:44.797892

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd59b5561d353'
down_revision = 'd0bc6ab51f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('inner_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'inner_html')
    # ### end Alembic commands ###
