"""Add height and width to media + videos table

Revision ID: e7c926c77c82
Revises: 8747fab65132
Create Date: 2025-10-02 13:10:38.032983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7c926c77c82'
down_revision = '8747fab65132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('images', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('video_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'media', 'videos', ['video_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'video_uuid')
    op.drop_column('images', 'width')
    op.drop_column('images', 'height')
    op.drop_table('videos')
    # ### end Alembic commands ###
